"""
Minimal OpenCL 1.2 low level ctypes API.
"""
from .OpenCL import (CL_DEVICE_EXTENSIONS, CL_DEVICE_GLOBAL_MEM_SIZE,
                     CL_DEVICE_MAX_COMPUTE_UNITS, CL_DEVICE_MAX_MEM_ALLOC_SIZE,
                     CL_DEVICE_MAX_WORK_GROUP_SIZE, CL_DEVICE_NAME,
                     CL_DEVICE_TYPE, CL_DEVICE_TYPE_ACCELERATOR,
                     CL_DEVICE_TYPE_ALL, CL_DEVICE_TYPE_CPU,
                     CL_DEVICE_TYPE_DEFAULT, CL_DEVICE_TYPE_GPU,
                     CL_DEVICE_VENDOR_ID, CL_DEVICE_VERSION, CL_DRIVER_VERSION,
                     CL_MEM_ALLOC_HOST_PTR, CL_MEM_COPY_HOST_PTR,
                     CL_MEM_READ_ONLY, CL_MEM_READ_WRITE, CL_MEM_SIZE,
                     CL_MEM_USE_HOST_PTR, CL_MEM_WRITE_ONLY,
                     CL_PLATFORM_EXTENSIONS, CL_PLATFORM_NAME,
                     CL_PLATFORM_PROFILE, CL_PLATFORM_VENDOR,
                     CL_PLATFORM_VERSION, CL_PROGRAM_BUILD_LOG,
                     CL_PROGRAM_BUILD_OPTIONS, CL_PROGRAM_BUILD_STATUS,
                     CLERROR, CLRESULT, byref, c_char, c_char_p, c_size_t,
                     c_void_p, cl_bitfield, cl_bool, cl_char, cl_command_queue,
                     cl_command_queue_properties, cl_context,
                     cl_context_properties, cl_device_id, cl_device_info,
                     cl_device_type, cl_double, cl_event, cl_float, cl_half,
                     cl_int, cl_kernel, cl_long, cl_mem, cl_mem_info,
                     cl_platform_id, cl_platform_info, cl_program,
                     cl_program_build_info, cl_short, cl_uchar, cl_uint,
                     cl_ulong, cl_ushort, clBuildProgram, clCreateBuffer,
                     clCreateCommandQueue, clCreateContext,
                     clCreateKernelsInProgram, clCreateProgramWithSource,
                     clEnqueueCopyBuffer, clEnqueueFillBuffer,
                     clEnqueueNDRangeKernel, clEnqueueReadBuffer,
                     clEnqueueWriteBuffer, clFinish, clGetDeviceIDs,
                     clGetDeviceInfo, clGetMemObjectInfo, clGetPlatformIDs,
                     clGetPlatformInfo, clGetProgramBuildInfo,
                     clReleaseCommandQueue, clReleaseContext, clReleaseEvent,
                     clReleaseKernel, clReleaseMemObject, clReleaseProgram,
                     clSetKernelArg, clWaitForEvents, create_string_buffer,
                     ctypes, sizeof)
